### ISSUE TITLE
Multiple colours progress element

### ISSUE THREAD

**Issue by tecpromotion** [forrestkirby/progress-element#4]
**Is your feature request related to a problem? Please describe.**
It should be possible to define one colour per progress element. This is best done in the element itself.

Furthermore, it would be great if these were multiple elements that could be easily copied. Like a grid element.

And it would be great if you could use the content from a dynamic content source.

**Comment by forrestkirby** [comment]
> It should be possible to define one colour per progress element. This is best done in the element itself.

Please check #5.

> Furthermore, it would be great if these were multiple elements that could be easily copied. Like a grid element.

This would require changing the element type to a multiple items element and changing the layout (at least to introduce some sort of grid). I don’t have any plans to change the item type or create a multiple items progress element at the moment.

> And it would be great if you could use the content from a dynamic content source.

It is already possible to use dynamic content for the content field as well as all settings.

![](https://content.screencast.com/users/forrestkirby/folders/YOOtheme/media/9d86e346-d5ee-4d89-9fcc-b404a105c0ee/04.22.2021-18.26.png)

Or did you refer to the color?
